### ISSUE TITLE
Replace builders of non-value classes by step builders

### ISSUE THREAD

**Issue by hoangtungdinh** [hoangtungdinh/BeSwarm#35]

**Comment by KrisC369** [comment]
Was the Choreography class refactored and merged in pull request #36 the only one affected by this issue?

**Comment by hoangtungdinh** [comment]
Nope. At first I want to have step builders for all classes using classical builders. However, I found that it is very difficult to combine step builder pattern with abstract builder pattern. Therefore I decided not to do that anymore.

**Comment by hoangtungdinh** [comment]
Abstract step builder(s) were implemented and tested in b44357765232c82b25f2a863a75af441c2c0b241
